# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 931)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1_fault = QtWidgets.QWidget()
        self.tab_1_fault.setObjectName("tab_1_fault")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_1_fault)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_layout = QtWidgets.QVBoxLayout()
        self.table_layout.setObjectName("table_layout")
        self.table_area_label = QtWidgets.QLabel(self.tab_1_fault)
        self.table_area_label.setObjectName("table_area_label")
        self.table_layout.addWidget(self.table_area_label)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1_fault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.table_layout.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.table_layout)
        self.graph_file = QtWidgets.QVBoxLayout()
        self.graph_file.setObjectName("graph_file")
        self.fault_graph_label = QtWidgets.QLabel(self.tab_1_fault)
        self.fault_graph_label.setObjectName("fault_graph_label")
        self.graph_file.addWidget(self.fault_graph_label)
        self.fault_graph = QtWidgets.QGraphicsView(self.tab_1_fault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fault_graph.sizePolicy().hasHeightForWidth())
        self.fault_graph.setSizePolicy(sizePolicy)
        self.fault_graph.setObjectName("fault_graph")
        self.graph_file.addWidget(self.fault_graph)
        self.selected_file_label = QtWidgets.QLabel(self.tab_1_fault)
        self.selected_file_label.setObjectName("selected_file_label")
        self.graph_file.addWidget(self.selected_file_label)
        self.file_name = QtWidgets.QLineEdit(self.tab_1_fault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_name.sizePolicy().hasHeightForWidth())
        self.file_name.setSizePolicy(sizePolicy)
        self.file_name.setObjectName("file_name")
        self.graph_file.addWidget(self.file_name)
        self.horizontalLayout.addLayout(self.graph_file)
        self.tabWidget.addTab(self.tab_1_fault, "")
        self.tab_2_est = QtWidgets.QWidget()
        self.tab_2_est.setObjectName("tab_2_est")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2_est)
        self.gridLayout.setObjectName("gridLayout")
        self.est_graph = QtWidgets.QGraphicsView(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_graph.sizePolicy().hasHeightForWidth())
        self.est_graph.setSizePolicy(sizePolicy)
        self.est_graph.setObjectName("est_graph")
        self.gridLayout.addWidget(self.est_graph, 1, 0, 1, 1)
        self.est_graph_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_graph_label.sizePolicy().hasHeightForWidth())
        self.est_graph_label.setSizePolicy(sizePolicy)
        self.est_graph_label.setObjectName("est_graph_label")
        self.gridLayout.addWidget(self.est_graph_label, 0, 0, 1, 1)
        self.est__measures_SRMs = QtWidgets.QVBoxLayout()
        self.est__measures_SRMs.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.est__measures_SRMs.setSpacing(0)
        self.est__measures_SRMs.setObjectName("est__measures_SRMs")
        self.est_gof_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_gof_label.sizePolicy().hasHeightForWidth())
        self.est_gof_label.setSizePolicy(sizePolicy)
        self.est_gof_label.setObjectName("est_gof_label")
        self.est__measures_SRMs.addWidget(self.est_gof_label)
        self.est_gof_measures = QtWidgets.QFormLayout()
        self.est_gof_measures.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.est_gof_measures.setContentsMargins(-1, -1, -1, 20)
        self.est_gof_measures.setHorizontalSpacing(15)
        self.est_gof_measures.setObjectName("est_gof_measures")
        self.est_LLF_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_LLF_label.sizePolicy().hasHeightForWidth())
        self.est_LLF_label.setSizePolicy(sizePolicy)
        self.est_LLF_label.setObjectName("est_LLF_label")
        self.est_gof_measures.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.est_LLF_label)
        self.est_LLF = QtWidgets.QLineEdit(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_LLF.sizePolicy().hasHeightForWidth())
        self.est_LLF.setSizePolicy(sizePolicy)
        self.est_LLF.setObjectName("est_LLF")
        self.est_gof_measures.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.est_LLF)
        self.est_AIC = QtWidgets.QLineEdit(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_AIC.sizePolicy().hasHeightForWidth())
        self.est_AIC.setSizePolicy(sizePolicy)
        self.est_AIC.setObjectName("est_AIC")
        self.est_gof_measures.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.est_AIC)
        self.est_BIC = QtWidgets.QLineEdit(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_BIC.sizePolicy().hasHeightForWidth())
        self.est_BIC.setSizePolicy(sizePolicy)
        self.est_BIC.setObjectName("est_BIC")
        self.est_gof_measures.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.est_BIC)
        self.est_AIC_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_AIC_label.sizePolicy().hasHeightForWidth())
        self.est_AIC_label.setSizePolicy(sizePolicy)
        self.est_AIC_label.setObjectName("est_AIC_label")
        self.est_gof_measures.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.est_AIC_label)
        self.est_BIC_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_BIC_label.sizePolicy().hasHeightForWidth())
        self.est_BIC_label.setSizePolicy(sizePolicy)
        self.est_BIC_label.setObjectName("est_BIC_label")
        self.est_gof_measures.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.est_BIC_label)
        self.est_MSE_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_MSE_label.sizePolicy().hasHeightForWidth())
        self.est_MSE_label.setSizePolicy(sizePolicy)
        self.est_MSE_label.setObjectName("est_MSE_label")
        self.est_gof_measures.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.est_MSE_label)
        self.est_MSE = QtWidgets.QLineEdit(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_MSE.sizePolicy().hasHeightForWidth())
        self.est_MSE.setSizePolicy(sizePolicy)
        self.est_MSE.setObjectName("est_MSE")
        self.est_gof_measures.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.est_MSE)
        self.est__measures_SRMs.addLayout(self.est_gof_measures)
        self.est_SRMs_label = QtWidgets.QLabel(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.est_SRMs_label.sizePolicy().hasHeightForWidth())
        self.est_SRMs_label.setSizePolicy(sizePolicy)
        self.est_SRMs_label.setObjectName("est_SRMs_label")
        self.est__measures_SRMs.addWidget(self.est_SRMs_label)
        self.est_list = QtWidgets.QListWidget(self.tab_2_est)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.est_list.sizePolicy().hasHeightForWidth())
        self.est_list.setSizePolicy(sizePolicy)
        self.est_list.setObjectName("est_list")
        item = QtWidgets.QListWidgetItem()
        self.est_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.est_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.est_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.est_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.est_list.addItem(item)
        self.est__measures_SRMs.addWidget(self.est_list)
        self.est_estimation_button = QtWidgets.QPushButton(self.tab_2_est)
        self.est_estimation_button.setObjectName("est_estimation_button")
        self.est__measures_SRMs.addWidget(self.est_estimation_button, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.est__measures_SRMs, 0, 1, 2, 1)
        self.tabWidget.addTab(self.tab_2_est, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_11.addWidget(self.label_30)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.formLayout_4.setHorizontalSpacing(15)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.verticalLayout_11.addLayout(self.formLayout_4)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_11.addWidget(self.label_35)
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_11.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_11.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_11.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_11.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_11.addWidget(self.radioButton_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_11.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addLayout(self.verticalLayout_11, 0, 2, 4, 1)
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_8.sizePolicy().hasHeightForWidth())
        self.graphicsView_8.setSizePolicy(sizePolicy)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.gridLayout_7.addWidget(self.graphicsView_8, 1, 0, 5, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_12.addWidget(self.label_37)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_12.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_12.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_12.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_12.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_12.addWidget(self.checkBox_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem1)
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_12.addWidget(self.label_38)
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_12.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_12.addWidget(self.radioButton_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.verticalLayout_12, 0, 1, 2, 1)
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_9.sizePolicy().hasHeightForWidth())
        self.graphicsView_9.setSizePolicy(sizePolicy)
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.gridLayout_3.addWidget(self.graphicsView_9, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.checkBox = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_10.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_10.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_10.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_10.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_10.addWidget(self.checkBox_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem3)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_10.addWidget(self.label_29)
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_10.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.verticalLayout_10, 0, 1, 2, 1)
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_7.sizePolicy().hasHeightForWidth())
        self.graphicsView_7.setSizePolicy(sizePolicy)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.gridLayout_6.addWidget(self.graphicsView_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1401, 26))
        self.menubar.setObjectName("menubar")
        self.menuf = QtWidgets.QMenu(self.menubar)
        self.menuf.setObjectName("menuf")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuf.addAction(self.actionOpen)
        self.menubar.addAction(self.menuf.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.table_area_label.setText(_translate("MainWindow", "Table area"))
        self.fault_graph_label.setText(_translate("MainWindow", "Graph"))
        self.selected_file_label.setText(_translate("MainWindow", "Selected file:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1_fault), _translate("MainWindow", "Fault data"))
        self.est_graph_label.setText(_translate("MainWindow", "Graph area"))
        self.est_gof_label.setText(_translate("MainWindow", "Goodness-of-fit measures"))
        self.est_LLF_label.setText(_translate("MainWindow", "LLF"))
        self.est_AIC_label.setText(_translate("MainWindow", "AIC"))
        self.est_BIC_label.setText(_translate("MainWindow", "BIC"))
        self.est_MSE_label.setText(_translate("MainWindow", "MSE"))
        self.est_SRMs_label.setText(_translate("MainWindow", "Selected SRMs"))
        __sortingEnabled = self.est_list.isSortingEnabled()
        self.est_list.setSortingEnabled(False)
        item = self.est_list.item(0)
        item.setText(_translate("MainWindow", "Geometric"))
        item = self.est_list.item(1)
        item.setText(_translate("MainWindow", "Discrete Weibull"))
        item = self.est_list.item(2)
        item.setText(_translate("MainWindow", "Discrete Weibull (order 2)"))
        item = self.est_list.item(3)
        item.setText(_translate("MainWindow", "Negative binomial"))
        item = self.est_list.item(4)
        item.setText(_translate("MainWindow", "Negative binomial (order 2)"))
        self.est_list.setSortingEnabled(__sortingEnabled)
        self.est_estimation_button.setText(_translate("MainWindow", "Estimation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2_est), _translate("MainWindow", "Estimation"))
        self.label_36.setText(_translate("MainWindow", "Graph area"))
        self.label_30.setText(_translate("MainWindow", "Goodness-of-fit measures"))
        self.label_31.setText(_translate("MainWindow", "LLF"))
        self.label_32.setText(_translate("MainWindow", "AIC"))
        self.label_33.setText(_translate("MainWindow", "BIC"))
        self.label_34.setText(_translate("MainWindow", "MSE"))
        self.label_35.setText(_translate("MainWindow", "Selected SRMs"))
        self.radioButton_7.setText(_translate("MainWindow", "Geometric"))
        self.radioButton_8.setText(_translate("MainWindow", "Negative binomial (order 2)"))
        self.radioButton_9.setText(_translate("MainWindow", "Discrete Weibull (order 2)"))
        self.radioButton_10.setText(_translate("MainWindow", "Negative binomial"))
        self.radioButton_11.setText(_translate("MainWindow", "Discrete Weibull"))
        self.pushButton_3.setText(_translate("MainWindow", "Estimation settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Statistical test"))
        self.label_39.setText(_translate("MainWindow", "Graph area"))
        self.label_37.setText(_translate("MainWindow", "Selected SRMs"))
        self.checkBox_6.setText(_translate("MainWindow", "Geometric"))
        self.checkBox_7.setText(_translate("MainWindow", "Negative binomial (order 2)"))
        self.checkBox_8.setText(_translate("MainWindow", "Discrete Weibull (order 2)"))
        self.checkBox_9.setText(_translate("MainWindow", "Negative binomial"))
        self.checkBox_10.setText(_translate("MainWindow", "Discrete Weibull"))
        self.label_38.setText(_translate("MainWindow", "Graphical display"))
        self.radioButton_12.setText(_translate("MainWindow", "Mean value function"))
        self.radioButton_13.setText(_translate("MainWindow", "Intensity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Mean value/intensity"))
        self.label_27.setText(_translate("MainWindow", "Graph area"))
        self.label_28.setText(_translate("MainWindow", "Selected SRMs"))
        self.checkBox.setText(_translate("MainWindow", "Geometric"))
        self.checkBox_2.setText(_translate("MainWindow", "Negative binomial (order 2)"))
        self.checkBox_3.setText(_translate("MainWindow", "Discrete Weibull (order 2)"))
        self.checkBox_4.setText(_translate("MainWindow", "Negative binomial"))
        self.checkBox_5.setText(_translate("MainWindow", "Discrete Weibull"))
        self.label_29.setText(_translate("MainWindow", "Graphical display"))
        self.radioButton_5.setText(_translate("MainWindow", "Mean value function"))
        self.radioButton_6.setText(_translate("MainWindow", "Intensity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Reliability/prediction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Validation"))
        self.menuf.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
